---
# tasks file for server
- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600
  become: yes

- name: Install required software
  apt: 
   name: [u'apache2', u'mysql-server', u'php7.2-mysql', u'php7.2', u'libapache2-mod-php7.2', u'python-mysqldb']